name: Tests

on: [pull_request]

jobs:
  phpunity-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests via PHPUnit
        env:
          APP_ENV: testing
          MULTIPAYMENT_DEFAULT: iugu
          IUGU_ID: ${{ secrets.IUGU_ID }}
          IUGU_APIKEY: ${{ secrets.IUGU_APIKEY }}
          MOIP_APITOKEN: ${{ secrets.MOIP_APITOKEN }}
          MOIP_APIKEY: ${{ secrets.MOIP_APIKEY }}
        run: composer test
